#!/bin/sh
# Begin $rc_base/init.d/dual-headers

### BEGIN INIT INFO
# Provides  :           dual-headers
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Short-Description:    test header parsing
# Description:          The dual-headers script has two LSB headers to
#  see if the parser can deal with that.
# X-Gado-Default-Start: S30
# X-Gado-Default-Stop:
### END INIT INFO

### BEGIN INIT INFO
# Provides  :           dual-headers
# Default-Start:        3 4 5
# Default-Stop:         0 1 2 6
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Short-Description:    test header parsing
# Description:          The dual-headers script has two LSB headers to
#  see if the parser can deal with that.
# X-Gado-Default-Start: S30
# X-Gado-Default-Stop:
### END INIT INFO

# Do some other stuff
case "$1" in
start)
	;;
stop)
	;;
esac
