#!/bin/sh
# Begin $rc_base/init.d/foo

### BEGIN INIT INFO
# Provides  :           foo
# Default-Start:        5
# Default-Stop:         0 1 2 3 4 6
# Required-Start:       $local_fs baz
# Required-Stop:        $local_fs baz
# Should-Start:
# Should-Stop:
# Short-Description:    test foo service
# Description:          The test service does cool 
#  stuff when
#	you start it
# X-Gado-Default-Start: S30
# X-Gado-Default-Stop:
### END INIT INFO

# Do some other stuff
case "$1" in
start)
	;;
stop)
	;;
esac
