#!/bin/sh
# Begin $rc_base/init.d/test-script

### BEGIN INIT INFO
# Provides:             foo bar
# Default-Start:        5
# Default-Stop:         0 1 2 3 4 6
# Required-Start:       $local_fs $network
# Required-Stop:        $local_fs $network
# Should-Start:         dbus
# Should-Stop:          dbus
# Short-Description:    start and stop test service
# Description:          The test service does cool
#  stuff when
#	you start it
# X-Gado-Default-Start: S30
# X-Gado-Default-Stop:
### END INIT INFO

# Do some other stuff
case "$1" in
start)
	;;
stop)
	;;
esac
